---
- name: Install supervisord packages.
  pip: >
    name={{ item }}
    state=latest
  with_items: supervisord_install_packages
  environment:
    PATH: "{{ supervisord_python_bin_directory }}:{{ ansible_env.PATH }}"
  when: supervisord_install_packages|length > 0

- name: Create supervisord conf and sub directory.
  file: >
    path="{{ supervisord_include_conf_directory }}"
    state=directory
    owner="{{ supervisord_user }}"
    group="{{ supervisord_group }}"
    mode=0755
  become: yes
- name: Create supervisord config file.
  template: >
    src=supervisord.conf.tpl
    dest="{{ supervisord_conf_directory }}/{{ supervisord_conf_file_name }}"
    owner="{{ supervisord_user }}"
    group="{{ supervisord_group }}"
    mode=0644

- name: Create supervisord log directory.
  file: >
    path="{{ supervisord_log_directory }}"
    state=directory
    owner="{{ supervisord_user }}"
    group="{{ supervisord_group }}"
    mode=0755
  become: yes
- name: Create supervisord pid directory.
  file: >
    path="{{ supervisord_pid_directory }}"
    state=directory
    owner="{{ supervisord_user }}"
    group="{{ supervisord_group }}"
    mode=0755
  become: yes
- name: Create supervisord http server socket directory.
  file: >
    path="{{ supervisord_unix_http_server_socket_directory }}"
    state=directory
    owner="{{ supervisord_user }}"
    group="{{ supervisord_group }}"
    mode=0755
  become: yes

- name: Create supervisord service file.
  template: >
    src=supervisord.tpl
    dest="/etc/rc.d/init.d/supervisord"
    mode=0755
  become: yes
  when: ansible_system == 'Linux'

- name: Register supervisord service.
  service: >
    name=supervisord
    enabled=yes
  become: yes
  when: ansible_system == 'Linux'
# - name: Start supervisord service.
#   service: >
#     name=supervisord
#     state=started
#   become: yes
#   when: ansible_system == 'Linux'
