---
- name: user list.
  shell: >
    cut -d: -f1 /etc/passwd
  register: user_list
  changed_when: false
  always_run: yes
  when: ansible_os_family != 'Darwin'
- name: Create supervisord user.
  user: >
    name="{{ supervisor_user }}"
    shell=/bin/false
    system=yes
    home="{{ supervisor_conf_directory }}"
    createhome=no
  when: ansible_os_family != 'Darwin' and user_list.stdout_lines.count(supervisor_user) < 1
  become: yes

- name: Install supervisord packages.
  pip: >
    name=supervisor
    state=latest
  environment:
    PATH: "{{ ansible_env.PATH }}"
  become: yes

- name: Create supervisord conf directory.
  file: >
    path="{{ supervisor_conf_directory }}"
    state=directory
    owner="{{ supervisor_user }}"
    group="{{ supervisor_group }}"
    mode=0755
  become: yes
- name: Create supervisord conf sub directory.
  file: >
    path="{{ supervisor_include_conf_directory }}"
    state=directory
    owner="{{ supervisor_user }}"
    group="{{ supervisor_group }}"
    mode=0755
  become: yes
- name: Create supervisord config file.
  template: >
    src=supervisord.conf.tpl
    dest="{{ supervisor_conf_directory }}/{{ supervisor_conf_file_name }}"
    owner="{{ supervisor_user }}"
    group="{{ supervisor_group }}"
    mode=0644
  become: yes

- name: Create supervisord log directory.
  file: >
    path="{{ supervisor_log_directory }}"
    state=directory
    owner="{{ supervisor_user }}"
    group="{{ supervisor_group }}"
    mode=0755
  become: yes
- name: Create supervisord pid directory.
  file: >
    path="{{ supervisor_pid_directory }}"
    state=directory
    owner="{{ supervisor_user }}"
    group="{{ supervisor_group }}"
    mode=0755
  become: yes
- name: Create supervisord http server socket directory.
  file: >
    path="{{ supervisor_unix_http_server_socket_directory }}"
    state=directory
    owner="{{ supervisor_user }}"
    group="{{ supervisor_group }}"
    mode=0755
  become: yes

- name: Create supervisord service file.
  template: >
    src=supervisord.service.tpl
    dest="/etc/rc.d/init.d/supervisord"
    mode=0755
  become: yes
  when: ansible_system == 'Linux'

- name: Register supervisord service.
  service: >
    name=supervisord
    enabled=yes
  become: yes
  when: ansible_system == 'Linux'
