---
- name: Install/Update terraform.
  homebrew_cask: >
    name=terraform
    state=present
  environment: 
    HOMEBREW_CASK_OPTS: "{{ homebrew_cask_options }}"

- name: Create terraform directory.
  file: >
    path="{{ terraform_directory }}"
    state=directory
    owner={{ terraform_user }}
    group={{ terraform_group }}
    mode=0755
  become: yes

- name: Insert env in .envrc.
  lineinfile: >
    dest={{ terraform_envrc_directory }}/.envrc
    line="{{ item.value }}"
    insertafter=EOF
    state=present
    regexp={{ item.regexp }}
  with_items: "{{ terraform_environment_variables }}"
  when: terraform_envrc_directory != '' and terraform_environment_variables|length > 0
