---
- name: Install gunicorn packages.
  pip: >
    name={{ item }}
    state=latest
  with_items: "{{ xbuild_gunicorn_install_packages }}"
  environment:
    PATH: "{{ xbuild_gunicorn_python_bin_directory }}:{{ ansible_env.PATH }}"
  when: xbuild_gunicorn_install_packages|length > 0

- name: Create gunicorn conf directory.
  file: >
    path="{{ xbuild_gunicorn_conf_directory }}"
    state=directory
    owner="{{ xbuild_gunicorn_user }}"
    group="{{ xbuild_gunicorn_group }}"
    mode=0755
  become: yes
- name: Create gunicorn config file.
  template: >
    src=gunicorn.conf.tpl
    dest="{{ xbuild_gunicorn_conf_directory }}/{{ xbuild_gunicorn_conf_file_name }}"
    owner="{{ xbuild_gunicorn_user }}"
    group="{{ xbuild_gunicorn_group }}"
    mode=0644
- name: Create gunicorn log directory.
  file: >
    path="{{ xbuild_gunicorn_log_directory }}"
    state=directory
    owner="{{ xbuild_gunicorn_user }}"
    group="{{ xbuild_gunicorn_group }}"
    mode=0755
  become: yes
- name: Create gunicorn pid directory.
  file: >
    path="{{ xbuild_gunicorn_pid_directory }}"
    state=directory
    owner="{{ xbuild_gunicorn_user }}"
    group="{{ xbuild_gunicorn_group }}"
    mode=0755
  become: yes

- name: Reload supervisord service.
  service: >
    name=supervisord
    state=reloaded
  when: ansible_system == 'Linux'
