---
- name: ansible_local json.
  stat: >
    path="{{ packer_aws_ansible_local_file }}"
  register: ansible_local_file
  changed_when: no
  check_mode: no
- name: Copy ansible json.
  copy: >
    src=ansible_local.json
    dest={{ packer_aws_ansible_local_file }}
    owner={{ packer_aws_user }}
    group={{ packer_aws_group }}
    mode=0644
  when: not ansible_local_file.stat.exists
  become: yes

- name: ansible json.
  stat: >
    path="{{ packer_aws_ansible_file }}"
  register: ansible_file
  changed_when: no
  check_mode: no
- name: Copy ansible json.
  copy: >
    src=ansible.json
    dest={{ packer_aws_ansible_file }}
    owner={{ packer_aws_user }}
    group={{ packer_aws_group }}
    mode=0644
  when: not ansible_file.stat.exists
  become: yes

- name: user data file.
  stat: >
    path="{{ packer_aws_user_data_file }}"
  register: user_data_file
  changed_when: no
  check_mode: no
- name: Copy user data file.
  copy: >
    src=user_data.txt
    dest={{ packer_aws_user_data_file }}
    owner={{ packer_aws_user }}
    group={{ packer_aws_group }}
    mode=0644
  when: not user_data_file.stat.exists
  become: yes

- name: Insert env in .envrc.
  lineinfile: >
    dest={{ packer_aws_envrc_directory }}/.envrc
    line="{{ item.value }}"
    insertafter=EOF
    state=present
    regexp={{ item.regexp }}
  with_items: "{{ packer_aws_environment_variables }}"
  when: packer_aws_envrc_directory != '' and packer_aws_environment_variables|length > 0
