---
- name: Install fabric.
  pip: >
    name=fabric
    state=present
  environment:
    PATH: "{{ fabric_python_bin_directory }}:{{ ansible_env.PATH }}"

- name: Copy fabfile.py.
  copy: >
    src=fabfile.py
    dest={{ fabric_tasks_file_directory }}/fabfile.py
    mode=0644
    force=yes
  become: yes

- name: Change fabfile.py owner.
  file: >
    path="{{ fabric_tasks_file_directory }}/fabfile.py"
    state=file
    owner={{ fabric_user }}
    group={{ fabric_group }}
  become: yes