- name: Install dependent packages(RedHat).
  become:     yes
  when:
    - "ansible_os_family == 'RedHat'"
    - "python_dependent_packages|length > 0"
  with_items: "{{ python_dependent_packages }}"
  yum:
    name:  "{{ item.name | default(item) }}"
    state: "{{ item.state | default('latest') }}"

- name: Install dependent packages(Darwin).
  when:
    - "ansible_os_family == 'Darwin'"
    - "python_dependent_packages|length > 0"
  with_items: "{{ python_dependent_packages }}"
  homebrew:
    name:            "{{ item.name | default(item) }}"
    state:           "{{ item.state | default(omit) }}"
    install_options: "{{ item.install_option | default(omit) }}"

- name: Clone xbuild directory.
  become:      yes
  become_user: "{{ project_user }}"
  git:
    repo:          "{{ nodejs_xbuild_repository }}"
    dest:          "{{ project_dir }}/xbuild"
    update:         yes
    accept_hostkey: yes

- name: Install nodejs in xbuild.
  become:      yes
  become_user: "{{ project_user }}"
  when:        "nodejs_install_versions|length > 0"
  with_items:  "{{ nodejs_install_versions }}"
  command:     "{{ project_dir }}/xbuild/node-install -f v{{ item.version }} {{ project_dir }}/node/versions/{{ item.version }} {{ nodejs_arch }}"

- name: Install nodejs packages.
  become:      yes
  become_user: "{{ project_user }}"
  when:        "nodejs_install_versions|length > 0"
  with_subelements:
    - "{{ nodejs_install_versions }}"
    - "packages"
  environment:
    PATH: "{{ project_dir }}/node/versions/{{ item.0.version }}/bin:{{ ansible_env.PATH }}"
  npm:
    name:       "{{ item.1.name | default(item.1) }}"
    production: "{{ item.1.production | default(omit) }}"
    global:     "{{ item.1.global | default(omit) }}"
    path:       "{{ item.0.path | default(omit) }}"
    version:    "{{ item.1.version | default(omit) }}"
    state:      "{{ item.1.state | default(omit) }}"
    executable: "{{ project_dir }}/node/versions/{{ item.0.version }}/bin/npm"


- name: Create alias directory.
  become: yes
  file:
    path:  "{{ project_dir }}/node/alias"
    owner: "{{ project_user }}"
    state: "directory"

- name: Create a default version of an alias.
  become: yes
  file:
    src:   "{{ project_dir }}/node/versions/{{ nodejs_default_version }}"
    dest:  "{{ project_dir }}/node/alias/default"
    owner: "{{ project_user }}"
    state: "link"

- name: Insert env in .envrc.
  become:      yes
  become_user: "{{ project_user }}"
  when:        "nodejs_environment_variables|length > 0"
  with_items:  "{{ nodejs_environment_variables }}"
  lineinfile:
    dest:        "{{ project_dir }}/.envrc"
    line:        "{{ item.value }}"
    insertafter: "EOF"
    state:       "present"
    regexp:      "{{ item.regexp }}"

- name: direnv allow.
  become: yes
  become_user: "{{ project_user }}"
  command: "direnv allow ./"
  args:
    chdir: "{{ project_dir }}"

- name: Remove xbuild directory.
  become: yes
  become_user: "{{ project_user }}"
  file:
    path:  "{{ project_dir }}/xbuild"
    state: "absent"
