---
- name: Install ansible.
  command: >
    {{ xbuild_ansible_python_bin_directory }}/pip install -U ansible

- name: Ansible directory.
  stat: >
    path={{ xbuild_ansible_directory }}
  register: home_directory
  changed_when: no
  always_run: yes
- name: Create ansible directory.
  file: >
    path="{{ xbuild_ansible_directory }}"
    state=directory
    mode=0755
  when: not home_directory.stat.exists

- name: Clone library roles repository.
  git: >
    repo="{{ xbuild_ansible_library_roles_repository }}"
    dest="{{ xbuild_ansible_directory }}/{{ xbuild_ansible_library_roles_directory_name }}"
    update=yes

- name: Default roles directory.
  stat: >
    path="{{ xbuild_ansible_default_roles_directory }}"
  register: default_directory
  changed_when: no
  always_run: yes

- name: Create default roles directory.
  file: >
    path="{{ xbuild_ansible_default_roles_directory }}"
    state=directory
    mode=0755
  when: not default_directory.stat.exists

- name: Clone main role repository.
  git: >
    repo="{{ xbuild_ansible_main_role_repository }}"
    dest="{{ xbuild_ansible_default_roles_directory }}/{{ xbuild_ansible_main_role_name }}"
    update=yes
  when: xbuild_ansible_main_role_repository

- name: Main role directory.
  stat: >
    path="{{ xbuild_ansible_default_roles_directory }}/{{ xbuild_ansible_main_role_name }}"
  register: main_role_directory
  changed_when: no
  always_run: yes
  when: not xbuild_ansible_main_role_repository and xbuild_ansible_default_roles_directory_name
- name: Create Main role directory.
  file: >
    path="{{ xbuild_ansible_default_roles_directory }}/{{ xbuild_ansible_default_roles_directory_name }}"
    state=directory
    mode=0755
  when: not xbuild_ansible_main_roles_repository and xbuild_ansible_default_roles_directory_name and not main_role_directory.stat.exists

- name: Playbook.
  stat: >
    path="{{ xbuild_ansible_playbook_file }}"
  register: playbook_file
  changed_when: no
  always_run: yes
- name: Create Playbook.
  template: >
    src=remote.yml.tpl
    dest="{{ xbuild_ansible_playbook_file }}"
    mode=0644
  when: not playbook_file.stat.exists

- name: Download buildout script.
  get_url: >
    url="{{ xbuild_ansible_buildout_script_url }}"
    dest="{{ xbuild_ansible_buildout_script }}"
    mode=755
    force=yes

- name: Change ansible directory owner.
  file: >
    path="{{ xbuild_ansible_directory }}"
    state=directory
    recurse=yes
    owner={{ xbuild_ansible_user }}
    group={{ xbuild_ansible_group }}
  become: yes

- name: Insert env in .envrc.
  lineinfile: >
    dest={{ xbuild_ansible_envrc_directory }}/.envrc
    line="{{ item.value }}"
    insertafter=EOF
    state=present
    regexp={{ item.regexp }}
  with_items: xbuild_ansible_environment_variables
  when: xbuild_ansible_envrc_directory != '' and xbuild_ansible_environment_variables|length > 0
