---
- name: Vagrant binary. 
  command: >
    which vagrant
  register: vagrant_bin
  ignore_errors: yes
  changed_when: no
  always_run: yes

- name: Install vagrant(Darwin).
  homebrew_cask: >
    name=vagrant
    state=present
  environment: 
    HOMEBREW_CASK_OPTS: "{{ homebrew_cask_options }}"
  when: vagrant_bin.rc == 1

- name: Install/Update vagrant-aws plug-in.
  command: >
    vagrant plugin install vagrant-aws

- name: Add vagrant-aws box.
  command: >
    vagrant box add --force {{ vagrant_aws_box_name }} {{ vagrant_aws_box_url }}

- name: Vagrant directory.
  stat: >
    path={{ vagrant_aws_vagarant_directory }}
  register: vagarant_directory 
  changed_when: no
  always_run: yes

- name: Create vagrant directory.
  file: >
    path="{{ vagrant_aws_vagarant_directory }}"
    state=directory
    mode=0755
  become: yes
  when: not vagarant_directory.stat.exists

- name: Create Vagrantfile.
  template: >
    src=Vagrantfile.tpl
    dest="{{ vagrant_aws_vagarant_directory }}/Vagrantfile"
    mode=0644

- name: Insert env in .envrc.
  lineinfile: >
    dest={{ vagrant_aws_envrc_directory }}/.envrc
    line="export {{ item.value }}"
    insertafter=EOF
    state=present
    regexp={{ item.regexp }}
  with_items: vagrant_aws_environment_variables
  when: vagrant_aws_envrc_directory != '' and vagrant_aws_environment_variables|length > 0
