---
- name: Vagrant binary. 
  command: >
    which vagrant
  register: vagrant_bin
  ignore_errors: yes
  changed_when: no
  always_run: yes

- name: Install vagrant(Darwin).
  homebrew_cask: >
    name=vagrant
    state=present
  environment: 
    HOMEBREW_CASK_OPTS: "{{ homebrew_cask_options }}"
  when: vagrant_bin.rc == 1

- name: Install/Update vagrant-aws plug-in.
  command: >
    vagrant plugin install vagrant-aws

- name: Vagrant box list.
  command: >
    vagrant box list
  register: vagrant_box_list
  changed_when: false
  always_run: yes

- name: Add vagrant-aws box.
  command: >
    vagrant box add {{ vagrant_aws_box_name }} {{ vagrant_aws_box_url }}
  when: vagrant_box_list.stdout_lines.count({{ vagrant_aws_box_name }}) < 1

# - name: Create Vagrantfile.
#   template: >
#     src=Vagrantfile.tpl
#     dest="{{ vagrant_aws_vagarant_directory }}/Vagrantfile"
#     mode=0644

# - name: Insert env in .envrc.
#   lineinfile: >
#     dest={{ vagrant_aws_envrc_directory }}/.envrc
#     line="export {{ item.value }}"
#     insertafter=EOF
#     state=present
#     regexp={{ item.regexp }}
#   with_items: vagrant_aws_environment_variables
#   when: vagrant_aws_envrc_directory != '' and vagrant_aws_environment_variables|length > 0
