---
- name: Install/Update vagrant-aws plug-in.
  command: >
    vagrant plugin install vagrant-aws

- name: Add vagrant-aws box.
  command: >
    vagrant box add --force {{ vagrant_aws_box_name }} {{ vagrant_aws_box_url }}

- name: Vagrant directory.
  stat: >
    path={{ vagrant_aws_vagarant_directory }}
  register: vagarant_directory 
  changed_when: no
  always_run: yes
- name: Create vagrant directory.
  file: >
    path="{{ vagrant_aws_vagarant_directory }}"
    state=directory
    mode=0755
  when: not vagarant_directory.stat.exists
  become: yes

- name: Create Vagrantfile.
  template: >
    src=Vagrantfile.tpl
    dest="{{ vagrant_aws_vagarant_directory }}/Vagrantfile"
    mode=0644
  become: yes

- name: Change vagrant directory owner.
  file: >
    path="{{ vagrant_aws_vagarant_directory }}"
    state=directory
    recurse=yes
    owner={{ vagrant_aws_user }}
    group={{ vagrant_aws_group }}
  become: yes

- name: Insert env in .envrc.
  lineinfile: >
    dest={{ vagrant_aws_envrc_directory }}/.envrc
    line="{{ item.value }}"
    insertafter=EOF
    state=present
    regexp={{ item.regexp }}
  with_items: vagrant_aws_environment_variables
  when: vagrant_aws_envrc_directory != '' and vagrant_aws_environment_variables|length > 0
