---
- name: Install/Upgrade dependent packages(RedHat).
  yum: >
    name={{ item.name | default(item) }}
    state={{ item.state | default('latest') }}
  with_items: "{{ locust_dependent_packages }}"
  when: ansible_os_family == 'RedHat' and locust_dependent_packages|length > 0
  become: yes

- name: Install locust packages.
  pip: >
    name={{ item }}
    state=latest
  with_items: "{{ locust_install_packages }}"
  environment:
    PATH: "{{ locust_python_bin_directory }}:{{ ansible_env.PATH }}"
  when: locust_install_packages|length > 0

- name: Create locust directory.
  file: >
    path="{{ locust_directory }}"
    state=directory
    owner="{{ locust_user }}"
    group="{{ locust_group }}"
    mode=0755
  become: yes

- name: Copy locust file.
  copy: >
    src=locustfile.py
    dest="{{ locust_directory }}/locustfile.py"
    owner="{{ locust_user }}"
    group="{{ locust_group }}"
    mode=0755

- name: Create locust log directory.
  file: >
    path="{{ locust_log_directory }}"
    state=directory
    owner="{{ locust_user }}"
    group="{{ locust_group }}"
    mode=0755
  become: yes

- name: Create supervisord process conf file of master.
  template: >
    src=master.conf.tpl
    dest={{ supervisord_include_conf_directory }}/locust.conf
    owner="{{ locust_user }}"
    group="{{ locust_group }}"
    mode=0644
  when: locust_is_master
  become: yes

- name: Create supervisord process conf file of slave.
  template: >
    src=slave.conf.tpl
    dest={{ supervisord_include_conf_directory }}/locust.conf
    owner="{{ locust_user }}"
    group="{{ locust_group }}"
    mode=0644
  when: not locust_is_master
  become: yes
