---
- name: Clone orchestration directory.
  git: >
    repo="{{ orchestration_repository }}"
    dest="{{ orchestration_directory }}"
    update=yes
    track_submodules=yes
    accept_hostkey=yes
  become: yes
  when: orchestration_repository != ''
- name: Create orchestration directory.
  file: >
    path="{{ orchestration_directory }}"
    state=directory
    mode=0755
  become: yes
  when: orchestration_repository == ''

- name: Change orchestration directory owner.
  file: >
    path="{{ orchestration_directory }}"
    state=directory
    recurse=yes
    owner={{ orchestration_user }}
    group={{ orchestration_group }}
  become: yes

- name: Insert env in .envrc.
  lineinfile: >
    dest={{ orchestration_envrc_directory }}/.envrc
    line="{{ item.value }}"
    insertafter=EOF
    state=present
    regexp={{ item.regexp }}
  with_items: orchestration_environment_variables
  when: orchestration_envrc_directory != '' and orchestration_environment_variables|length > 0

