---
- name: Install fluentd packages.
  gem: >
    name={{ item }}
    state=latest
    executable={{ fluentd_ruby_bin_directory }}/gem
    user_install=no
  with_items: "{{ fluentd_install_packages }}"
  when: fluentd_install_packages|length > 0