---
- name: Go directory.
  stat: >
    path={{ xbuild_go_install_directory }}
  register: go_dir
  changed_when: False
  always_run: yes
- name: Install go in xbuild.
  command: >
    {{ xbuild_install_directory }}/go-install {{ xbuild_go_version }}
    {{ xbuild_go_install_directory }} {{ xbuild_go_os }} {{ xbuild_go_arch }}
  when: not go_dir.stat.exists
- name: Remove xbuild directory.
  file: >
    path={{ xbuild_install_directory }}
    state=absent
  when: xbuild_go_remove_xbuild
- name: Change go directory owner.
  file: >
    path={{ xbuild_go_install_directory }}
    state=directory
    recurse=yes
    owner={{ xbuild_go_user }}
    group={{ xbuild_go_group }}
  become: yes

