- name: Install selenium.
  pip: >
    name=selenium
    state=latest
    executable={{ python_selenium_bin_directory }}/pip

- name: Install xvfbwrapper.
  pip: >
    name=xvfbwrapper
    state=latest
    executable={{ python_selenium_bin_directory }}/pip
