---
- name: Install dependent packages(RedHat).
  yum: >
    name={{ item.name | default(item) }}
    state={{ item.state | default('latest') }}
  with_items: xbuild_python_dependent_packages
  when: ansible_os_family == 'RedHat' and xbuild_python_dependent_packages|length > 0
- name: Install dependent packages(Darwin).
  homebrew: >
    name={{ item.name | default(item) }}
    state={{ item.state | default('latest') }}
    install_options={{ item.install_option | default('') }}
  with_items: xbuild_python_dependent_packages
  when: ansible_os_family == 'Darwin' and xbuild_python_dependent_packages|length > 0

- name: Python directory.
  stat: >
    path={{ xbuild_python_install_directory }}
  register: python_dir
  changed_when: no
  always_run: yes
- name: Install python in xbuild.
  command: >
    {{ xbuild_install_directory }}/python-install {{ xbuild_python_version }}
    {{ xbuild_python_install_directory }}
  when: not python_dir.stat.exists
- name: Install python packages.
  command: >
    {{ xbuild_python_install_directory }}/bin/pip install {{ item }}
  with_items: xbuild_python_packages
  when: xbuild_python_packages|length > 0
- name: Change python directory owner.
  file: >
    path={{ xbuild_python_install_directory }}
    state=directory
    recurse=yes
    owner={{ xbuild_python_user }}
    group={{ xbuild_python_group }}
  become: yes

- name: Remove xbuild directory.
  file: >
    path={{ xbuild_install_directory }}
    state=absent
  when: xbuild_python_remove_xbuild

- name: Resource File.
  stat: >
    path={{ xbuild_python_resource_file }}
  register: rc_file
  when: xbuild_python_resource_file

- name: "Create {{ xbuild_python_resource_file }}."
  file: >
    state=touch
    path={{ xbuild_python_resource_file }}
    owner={{ xbuild_python_user }}
    group={{ xbuild_python_user }}
    mode=0644
  when: xbuild_python_resource_file

- name: Add python bin Path.
  lineinfile: >
    dest={{ rc_file }}
    line="export PATH={{ xbuild_python_install_directory }}/bin:$PATH"
    insertafter=EOF
    state=present
    regexp="/python/bin\:\$PATH"
  when: xbuild_python_resource_file


