---
# - name: Install dependent packages(RedHat).
#   yum: >
#     name={{ item.name | default(item) }}
#     state={{ item.state | default('latest') }}
#   with_items: xbuild_python_dependent_packages
#   when: ansible_os_family == 'RedHat' or xbuild_python_dependent_packages|length > 0
# - name: Install dependent packages(Darwin).
#   homebrew: >
#     name={{ item.name | default(item) }}
#     state={{ item.state | default('latest') }}
#     install_options={{ item.install_option | default('') }}
#   with_items: xbuild_python_dependent_packages
#   when: ansible_os_family == 'Darwin' or xbuild_python_dependent_packages|length > 0
# - name: Python directory.
#   stat: >
#     path=xbuild_python_install_directory
#   register: res
#   changed_when: False
#   always_run: yes
# - name: Install python in xbuild.
#   command: >
#     {{ xbuild_install_directory }}/python-install {{ xbuild_python_version }}
#     {{ xbuild_python_install_directory }}
#   when: not res.stat.exists
# - name: Remove xbuild directory.
#   file: >
#     path=xbuild_install_directory
#     state=absent
#   when: xbuild_python_remove_xbuild
- name: Change python directory owner.
  file: >
    path="{{ xbuild_python_install_directory }}"
    state=directory
    recurse=yes
    owner="{{ xbuild_python_user }}"
    group="{{ xbuild_python_group }}"
  become: yes
# - name: Change python directory owner.
#   command: >
#     chown -R {{ xbuild_python_user }}:{{ xbuild_python_group }} {{ xbuild_python_install_directory }}
#   become: yes
  become: yes

