---
- name: Install invoke.
  pip: >
    name=invoke
    state=latest
  environment:
    PATH: "{{ cmdtools_python_bin_directory }}:{{ ansible_env.PATH }}"

- name: Install ansible.
  command: >
    {{ cmdtools_python_bin_directory }}/pip install -U ansible

- name: Copy tasks.py.
  copy: >
    src=tasks.py
    dest={{ cmdtools_tasks_file_directory }}/tasks.py
    mode=0644
    force=yes