---
- name: Stop nginx service.
  service: >
    name=nginx
    state=stopped
  when: ansible_system == 'Linux'
  become: yes

- name: Replace http.server.conf.
  template: >
    src=nginx.http.server.conf.tpl
    dest={{ proxy_gunicorn_nginx_directory }}/conf/conf.d/http.server.conf
    owner="{{ proxy_gunicorn_user }}"
    group="{{ proxy_gunicorn_group }}"
    mode=0644
  become: yes

