---
- name: user list.
  shell: >
    cut -d: -f1 /etc/passwd  
  register: user_list  
  changed_when: false  
  always_run: yes
  when: ansible_os_family != 'Darwin'
- name: Create ffmpeg user.
  user: >
    name="{{ ffmpeg_user }}"
    shell=/bin/false
    system=yes
    home="{{ ffmpeg_prefix }}"
    createhome=no
  when: ansible_os_family != 'Darwin' and user_list.stdout_lines.count(ffmpeg_user) < 1 
  become: yes

- name: Install/Upgrade dependent packages(RedHat).
  yum: >
    name={{ item.name | default(item) }}
    state={{ item.state | default('latest') }}
  with_items: "{{ ffmpeg_dependent_packages }}"
  when: ansible_os_family == 'RedHat' and ffmpeg_dependent_packages|length > 0
  become: yes

- name: Create work directory.
  file: >
    path="{{ ffmpeg_work_directory }}"
    state=directory
    owner="{{ ffmpeg_user }}"
    group="{{ ffmpeg_group }}"
    mode=0755
  become: yes

- name: Clone yasm repository.
  git: >
    repo={{ ffmpeg_yasm_repository }}
    dest={{ ffmpeg_work_directory }}/yasm
    update=yes
    accept_hostkey=yes
  become: yes

- name: Configure, Make and Install yasm.
  shell: "{{ item }}" 
  args:
    chdir: "{{ ffmpeg_work_directory }}/yasm" 
  with_items:
    - autoreconf -fiv
    - "./configure --prefix='{{ ffmpeg_prefix }}'"
    - make
    - make install
  become: yes
