---
- name: Clone project directory.
  git: >
    repo="{{ project_repository }}"
    dest="{{ project_directory }}"
    update=yes
    track_submodules=yes
  become: yes
  when: project_repository != ''
- name: Create project directory.
  file: >
    path="{{ project_directory }}"
    state=directory
    mode=0755
  become: yes
  when: project_repository == ''

- name: Change project directory owner.
  file: >
    path="{{ project_directory }}"
    state=directory
    recurse=yes
    owner={{ project_user }}
    group={{ project_group }}
  become: yes
