---
- name: Create project directory.
  file: >
    path="{{ project_directory }}"
    owner={{ project_user }}
    group={{ project_group }}
    state=directory
    mode=0755
  become: yes

- name: Create key directory.
  file: >
    path="{{ project_key_directory }}"
    state=directory
    recurse=yes
    owner={{ project_user }}
    group={{ project_group }}
    mode=0755
  when: project_local_private_key != ''
- name: Copy private key for git.
  copy: >
    src="{{ project_local_private_key }}"
    dest="{{ project_private_key }}"
    mode=0400
  when: project_local_private_key != ''
- name: Create git_ssh file.
  template: >
    src=git_ssh.tpl
    dest="{{ project_git_ssh_file }}"
    owner="{{ project_user }}"
    group="{{ project_group }}"
    mode=0755
  when: project_local_private_key != ''

- name: Clone repository.
  git: >
    repo="{{ project_repository }}"
    dest="{{ project_directory }}"
    track_submodules=true
    version="{{ project_repository_version }}"
    accept_hostkey=true
    force=true
  environment:
    GIT_SSH: "{{ project_git_ssh_file }}"
  ignore_errors: yes
  when: project_repository != ''

- name: Remove key directory.
  file: >
    path={{ project_key_directory }}
    state=absent
  when: project_local_private_key != ''

- name: Remove .git.
  file: >
    path={{ project_directory }}/.git
    state=absent
  when: project_repository == 'https://github.com/ojos/project-skel.git'
- name: git init.
  command: "git init {{ project_directory }}"
  when: project_repository == 'https://github.com/ojos/project-skel.git'

# - name: Change project directory owner.
#   file: >
#     path="{{ project_directory }}"
#     state=directory
#     recurse=yes
#     owner={{ project_user }}
#     group={{ project_group }}
#   become: yes
