---
- name: Install dependent packages(RedHat).
  yum: >
    name={{ item.name | default(item) }}
    state={{ item.state | default('latest') }}
  become: yes
  with_items: "{{ openresty_luarocks_dependent_packages }}"
  when: ansible_os_family == 'RedHat' and openresty_luarocks_dependent_packages|length > 0
- name: Install dependent packages(Darwin).
  homebrew: >
    name={{ item.name | default(item) }}
    state={{ item.state | default('latest') }}
    install_options={{ item.install_option | default('') }}
  with_items: "{{ openresty_luarocks_dependent_packages }}"
  when: ansible_os_family == 'Darwin' and openresty_luarocks_dependent_packages|length > 0

- name: Create work directory.
  file: >
    path="{{ openresty_luarocks_work_directory }}"
    state=directory
    owner="{{ openresty_luarocks_user }}"
    group="{{ openresty_luarocks_group }}"
    mode=0777
  become: yes

- name: Extract luarocks source.
  unarchive: >
    src="http://luarocks.org/releases/luarocks-{{ openresty_luarocks_version }}.tar.gz"
    dest="{{ openresty_luarocks_work_directory }}"
    copy=no
  become: yes

- name: Configure, Make and Install luarocks.
  shell: "{{ item }}" 
  args:
    chdir: "{{ openresty_luarocks_work_directory }}/luarocks-{{ openresty_luarocks_version }}"
  with_items:
    - "./configure {{ openresty_luarocks_configure_options }}"
    - make build
    - make install
  become: yes

- name: Remove work directory.
  file: >
    path="{{ openresty_luarocks_work_directory }}"
    state=absent
  become: yes

- name: luarocks path.
  shell: >
    {{ openresty_luarocks_bin_file }} path | sed "s/export.*'\(.*\)'/\1;;/"
  register: luarocks_path_list

- name: Replace lua_package_path.
  replace: >
    dest="{{ openresty_luarocks_nginx_lua_conf_file }}"
    replace="\1'{{ openresty_luarocks_nginx_directory }}/lua/?.lua;{{ luarocks_path_list.stdout_lines[0] }}';"
    regexp="(^lua_package_path\s+)'.*';"
  become: yes
- name: Replace lua_package_cpath.
  replace: >
    dest="{{ openresty_luarocks_nginx_lua_conf_file }}"
    replace="\1'{{ luarocks_path_list.stdout_lines[1] }}';"
    regexp="(^lua_package_cpath\s+)'.*';"
  become: yes

- name: Change openresty directory owner.
  file: >
    path="{{ openresty_luarocks_openresty_directory }}"
    state=directory
    recurse=yes
    owner="{{ openresty_luarocks_user }}"
    group="{{ openresty_luarocks_group }}"
  become: yes

- name: Install luarocks packages.
  shell: >
    {{ openresty_luarocks_bin_file }} install {{ item }}
  with_items: "{{ openresty_luarocks_install_packages }}"
  when: openresty_luarocks_install_packages|length > 0
  become: yes
  become_user: "{{ openresty_luarocks_user }}"

- name: Insert env in .envrc.
  lineinfile: >
    dest={{ openresty_luarocks_envrc_directory }}/.envrc
    line="{{ item.value }}"
    insertafter=EOF
    state=present
    regexp={{ item.regexp }}
  with_items: "{{ openresty_luarocks_environment_variables }}"
  when: openresty_luarocks_envrc_directory != '' and openresty_luarocks_environment_variables|length > 0

