---
- name: Extract luarocks source.
  unarchive: >
    src="http://luarocks.org/releases/luarocks-{{ openresty_luarocks_version }}.tar.gz"
    dest="{{ openresty_luarocks_src_directory }}"
    copy=no
  become: yes

- name: Configure luarocks source.
  shell: >
    ./configure {{ openresty_luarocks_configure_options }}
  args:
    chdir: "{{ openresty_luarocks_src_directory }}/luarocks-{{ openresty_luarocks_version }}"
  become: yes

- name: Made file.
  stat: >
    path="{{ openresty_luarocks_src_directory }}/luarocks-{{ openresty_luarocks_version }}/made"
  register: made_file
  changed_when: no
  always_run: yes
- name: Build luarocks.
  shell: >
    /usr/bin/make build
  args:
    chdir: "{{ openresty_luarocks_src_directory }}/luarocks-{{ openresty_luarocks_version }}"
  become: yes
  when: not made_file.stat.exists or openresty_luarocks_force_install

- name: Touch Maked file.
  file: >
    path={{ openresty_luarocks_src_directory }}/luarocks-{{ openresty_luarocks_version }}/made
    state=touch
  become: yes
  when: not made_file.stat.exists

- name: Binary file.
  stat: >
    path={{ openresty_luarocks_prefix }}/bin/luarocks
  register: bin_file
  changed_when: no
  always_run: yes
- name: Install luarocks.
  shell: >
    /usr/bin/make install
  args:
    chdir: "{{ openresty_luarocks_src_directory }}/luarocks-{{ openresty_luarocks_version }}"
  when: not bin_file.stat.exists or openresty_luarocks_force_install
  become: yes
  become_user: "{{ openresty_luarocks_user }}"

- name: Remove source directory.
  file: >
    path="{{ openresty_luarocks_src_directory }}/luarocks-{{ openresty_luarocks_version }}"
    state=absent
  become: yes
  when: openresty_luarocks_remove_src_directory

- name: Change luajit directory owner.
  file: >
    path="{{ openresty_luarocks_prefix }}"
    state=directory
    recurse=yes
    owner="{{ openresty_luarocks_user }}"
    group="{{ openresty_luarocks_group }}"
  become: yes

- name: Install luarocks packages.
  shell: >
    {{ openresty_luarocks_bin_file }} install {{ item }}
  with_items: "{{ openresty_luarocks_install_packages }}"
  when: openresty_luarocks_install_packages|length > 0
  become: yes
  become_user: "{{ openresty_luarocks_user }}"

