---
- name: Extract luarocks source.
  unarchive: >
    src="http://luarocks.org/releases/luarocks-{{ openresty_luarocks_version }}.tar.gz"
    dest="{{ openresty_luarocks_src_directory }}"
    copy=no
  become: yes

- name: Make file.
  stat: >
    path="{{ openresty_luarocks_src_directory }}/luarocks-{{ openresty_luarocks_version }}/Makefile"
  register: make_file
  changed_when: no
  always_run: yes

- name: debug.
  debug: >
    msg="{{ openresty_luarocks_configure_options }}"

- name: Configure luarocks source.
  shell: >
    ./configure {{ openresty_luarocks_configure_options }}
  args:
    chdir: "{{ openresty_luarocks_src_directory }}/luarocks-{{ openresty_luarocks_version }}"
  become: yes
  when: not make_file.stat.exists or openresty_luarocks_force_install

- name: Made file.
  stat: >
    path="{{ openresty_luarocks_src_directory }}/luarocks-{{ openresty_luarocks_version }}/made"
  register: made_file
  changed_when: no
  always_run: yes
- name: Make luarocks.
  shell: >
    /usr/bin/make
  args:
    chdir: "{{ openresty_luarocks_src_directory }}/luarocks-{{ openresty_luarocks_version }}"
  become: yes
  when: not made_file.stat.exists or openresty_luarocks_force_install

- name: Touch Maked file.
  file: >
    path={{ openresty_luarocks_src_directory }}/luarocks-{{ openresty_luarocks_version }}/made
    state=touch
  become: yes
  when: not made_file.stat.exists

- name: Binary file.
  stat: >
    path={{ openresty_luarocks_luajit_prefix }}/bin/luarocks
  register: bin_file
  changed_when: no
  always_run: yes
- name: Install luarocks.
  shell: >
    /usr/bin/make install
  args:
    chdir: "{{ luarocks_src_directory }}/luarocks-{{ luarocks_version }}"
  become: yes
  when: not bin_file.stat.exists or luarocks_force_install

- name: Remove source directory.
  file: >
    path="{{ luarocks_src_directory }}/luarocks-{{ luarocks_version }}"
    state=absent
  become: yes
  when: luarocks_nginx_remove_src_directory