---
- name: Install dependent packages(RedHat).
  yum: >
    name={{ item.name | default(item) }}
    state={{ item.state | default('latest') }}
  become: yes
  with_items: "{{ kcl_python_dependent_packages }}"
  when: ansible_os_family == 'RedHat' and kcl_python_dependent_packages|length > 0
- name: Install dependent packages(Darwin).
  homebrew_cask: >
    name={{ item.name | default(item) }}
    state={{ item.state | default('present') }}
  with_items: "{{ kcl_python_dependent_packages }}"
  when: ansible_os_family == 'Darwin' and kcl_python_dependent_packages|length > 0
  environment:
    HOMEBREW_CASK_OPTS: "{{ homebrew_cask_options }}"

- name: Install Kcl/Py packages.
  pip: >
    name={{ item }}
    state=latest
    executable={{ supervisor_executable_pip }}
  with_items: "{{ kcl_python_install_packages }}"
  when: kcl_python_install_packages|length > 0


- name: Create Kcl/Py conf directory.
  file: >
    path="{{ kcl_python_conf_directory }}"
    state=directory
    owner="{{ kcl_python_user }}"
    group="{{ kcl_python_group }}"
    mode=0755
  become: yes

- name: Copy executable file.
  copy: >
    src=kcl_app.py
    dest="{{ kcl_python_conf_directory }}/{{ kcl_python_executable_file_name }}"
    owner="{{ kcl_python_user }}"
    group="{{ kcl_python_group }}"
    mode=0755
  become: yes

- name: Create properties file.
  template: >
    src=kcl_app.properties.tpl
    dest="{{ kcl_python_conf_directory }}/{{ kcl_python_properties_file_name }}"
    owner="{{ kcl_python_user }}"
    group="{{ kcl_python_group }}"
    mode=0644
  become: yes

- name: java binary.
  shell: >
    which java
  register: java_path
  changed_when: false
  check_mode: no


- name: Create supervisord process conf file.
  template: >
    src=supervisord.conf.tpl
    dest={{ supervisor_include_conf_directory }}/kclpy.conf
    owner="{{ kcl_python_user }}"
    group="{{ kcl_python_user }}"
    mode=0644
  become: yes
