---
- name: Install celery packages.
  pip: >
    name={{ item }}
    state=latest
  with_items: "{{ xbuild_celery_install_packages }}"
  environment:
    PATH: "{{ xbuild_celery_python_bin_directory }}:{{ ansible_env.PATH }}"
  when: xbuild_celery_install_packages|length > 0

- name: Create celery conf directory.
  file: >
    path="{{ xbuild_celery_conf_directory }}"
    state=directory
    owner="{{ xbuild_celery_user }}"
    group="{{ xbuild_celery_group }}"
    mode=0755
  become: yes
- name: Create celery config file.
  template: >
    src=celery.conf.tpl
    dest="{{ xbuild_celery_conf_directory }}/{{ xbuild_celery_conf_file_name }}"
    owner="{{ xbuild_celery_user }}"
    group="{{ xbuild_celery_group }}"
    mode=0644
- name: Create celery log directory.
  file: >
    path="{{ xbuild_celery_log_directory }}"
    state=directory
    owner="{{ xbuild_celery_user }}"
    group="{{ xbuild_celery_group }}"
    mode=0755
  become: yes
- name: Create celery pid directory.
  file: >
    path="{{ xbuild_celery_pid_directory }}"
    state=directory
    owner="{{ xbuild_celery_user }}"
    group="{{ xbuild_celery_group }}"
    mode=0755
  become: yes

- name: Reload supervisord service.
  service: >
    name=supervisord
    state=reloaded
  when: ansible_system == 'Linux'
