---
- name: Install ansible.
  command: >
    {{ ansible_python_bin_directory }}/pip install -U ansible

- name: Ansible directory.
  stat: >
    path={{ ansible_directory }}
  register: ansb_directory 
  changed_when: no
  always_run: yes

- name: Clone buildout repository.
  git: >
    repo="{{ ansible_buildout_repository }}"
    dest="{{ ansible_directory }}"
    update=yes
  when: not ansb_directory.stat.exists

- name: Insert env in .envrc.
  lineinfile: >
    dest={{ ansible_envrc_directory }}/.envrc
    line="{{ item.value }}"
    insertafter=EOF
    state=present
    regexp={{ item.regexp }}
  with_items: ansible_environment_variables
  when: ansible_envrc_directory != '' and ansible_environment_variables|length > 0
