---
- name: Create nginx user.
  user: >
    name="{{ nginx_user }}"
    shell=/bin/false
    system=yes
    home="{{ nginx_prefix_dir }}"
    createhome=no
  ignore_errors: True
- name: Install dependent packages.
  yum: >
    name="{{ item }}"
    state="present"
  with_items: "{{ nginx_dependent_packages }}"
# - name: Clone ngx_devel_kit repository.
#   git: >
#     repo="{{ nginx_ngx_devel_kit_repo }}"
#     dest="{{ nginx_ngx_devel_kit_src_dir }}"
#     update="yes"
#     accept_hostkey="yes"
# - name: Clone nginx_lua_module repository.
#   git: >
#     repo="{{ nginx_lua_module_repo }}"
#     dest="{{ nginx_lua_module_src_dir }}"
#     update="yes"
#     accept_hostkey="yes"
# - name: Download nginx source.
#   get_url: >
#     url=http://nginx.org/download/nginx-{{ nginx_version }}.tar.gz
#     dest="{{ nginx_src_dir }}/nginx-{{ nginx_version }}.tar.gz"
#     force="yes"
# - name: Extract nginx source.
#   unarchive: >
#     src="{{ nginx_src_dir }}/nginx-{{ nginx_version }}.tar.gz"
#     dest="{{ nginx_src_dir }}"
#     copy="no"
# - name: Configure nginx source.
#   shell: >
#     export LUAJIT_LIB={{ nginx_luaJIT_lib_dir }} &&
#     export LUAJIT_INC={{ nginx_luaJIT_inc_dir }} &&
#     ./configure {{ nginx_configure_options }}
#     chdir={{ nginx_src_dir }}/nginx-{{ nginx_version }}
# - name: Make nginx.
#   shell: >
#     export LUAJIT_LIB={{ nginx_luaJIT_lib_dir }} &&
#     export LUAJIT_INC={{ nginx_luaJIT_inc_dir }} &&
#     /usr/bin/make
#     chdir={{ nginx_src_dir }}/nginx-{{ nginx_version }}
# - name: Install nginx.
#   shell: >
#     export LUAJIT_LIB={{ nginx_luaJIT_lib_dir }} &&
#     export LUAJIT_INC={{ nginx_luaJIT_inc_dir }} &&
#     /usr/bin/make install
#     chdir={{ nginx_src_dir }}/nginx-{{ nginx_version }}
# - name: Copy favicon.ico.
#   copy: >
#     src=favicon.ico
#     dest={{ nginx_prefix_dir }}/html/favicon.ico
#     owner=root
#     group=root
#     mode=0644
# - name: Create nginx sysconfig file.
#   template: >
#     src=sysconfig.tpl
#     dest="{{ nginx_sysconfig_file }}"
#     owner=root
#     group=root
#     mode=0644
# - name: Create nginx service file.
#   template: >
#     src=service.tpl
#     dest="{{ nginx_service_file }}"
#     owner=root
#     group=root
#     mode=0755
# - name: Register and Start nginx service.
#   service: >
#     name=nginx
#     state=started
#     enabled=yes
