- name: Install dependent packages(Amazon Linux).
  yum: >
    name={{ item.name | default(item) }}
    state={{ item.state | default('latest') }}
  with_items: "{{ firefox_dependent_packages }}"
  when: ansible_distribution == 'Amazon' and firefox_dependent_packages|length > 0
  become: yes

- name: Download install shell.
  get_url: >
    url={{ firefox_install_shell_url}}
    dest={{ firefox_install_shell_file }}
    mode=0755
  when: ansible_distribution == 'Amazon'
  become: yes

- name: Replace archive url.
  lineinfile: >
    dest={{ firefox_install_shell_file }}
    regexp='^(.+)http://download.cdn.mozilla.net.+$'
    line="\1{{ firefox_install_archive_url }}"
    state=present
    insertafter=EOF
    backrefs=yes
  when: ansible_distribution == 'Amazon'
  become: yes

- name: Install Firefox(AmazonLinux).
  shell: >
    {{ firefox_install_shell_file }}
  when: ansible_distribution == 'Amazon'
  become: yes

- name: Remove libpixman-1.so.0.
  file: >
    path=/usr/local/lib/libpixman-1.so.0
    state=absent
  when: ansible_distribution == 'Amazon'
  become: yes

- name: Install Firefox(Darwin).
  homebrew_cask: >
    name=firefox
    state=present
  when: ansible_os_family == 'Darwin'
  environment: 
    HOMEBREW_CASK_OPTS: "{{ homebrew_cask_options }}"