---
- name: Stop nginx service.
  service: >
    name=nginx
    state=stopped
    enabled=yes
- name: Change nginx.conf.
  template: >
    src=nginx.conf.tpl
    dest=/etc/nginx/nginx.conf
    owner=root
    group=root
    mode=0644
- name: Install passlib.
  pip: name=passlib
- name: Create htpassword.
  htpasswd: >
    path="{{ proxy_s3_htpassword }}"
    name="{{ proxy_s3_username }}"
    password="{{ proxy_s3_password }}"
    owner=root
    group=nginx
    mode=0640
- name: Start nginx service.
  service: >
    name=nginx
    state=started
    enabled=yes
