---
- name: Stop nginx service.
  service: >
    name=nginx
    state=stopped
  when: ansible_system == 'Linux'
  become: yes

- name: Install luarocks packages.
  shell: >
    {{ proxy_s3_luarocks_bin_file }} install {{ item }}
  with_items: proxy_s3_luarocks_install_packages
  when: proxy_s3_luarocks_install_packages|length > 0
  become: yes
  become_user: "{{ proxy_s3_user }}"

- name: Replace http.server.conf.
  template: >
    src=nginx.http.server.conf.tpl
    dest={{ nginx_home_dir.stdout }}/conf/conf.d/http.server.conf
    owner="{{ proxy_s3_user }}"
    group="{{ proxy_s3_group }}"
    mode=0644
  become: yes

