---
- name: Stop nginx service.
  service: >
    name=nginx
    state=stopped
  when: ansible_system == 'Linux'
  become: yes

- name: Replace http.server.conf.
  template: >
    src=nginx.http.server.conf.tpl
    dest={{ proxy_s3_nginx_sub_conf_directory }}/http.server.conf
    owner="{{ proxy_s3_user }}"
    group="{{ proxy_s3_group }}"
    mode=0644
  become: yes

- name: Install passlib.
  pip: >
    name=passlib
    state=latest
  become: yes

- name: Create htpassword.
  htpasswd: >
    path="{{ proxy_s3_nginx_conf_prefix }}/{{ proxy_s3_htpassword_file_name }}"
    name="{{ proxy_s3_auth_username }}"
    password="{{ proxy_s3_auth_password }}"
    owner=root
    group=nginx
    mode=0640
