---
- name: Deploy Source.
  git: >
    repo={{ item.repository }}
    dest={{ item.directory }}
    update=yes
    force=yes
    track_submodules=yes
    accept_hostkey=yes
  with_items: "{{ deploy_sources }}"
  when: deploy_sources|length > 0
  become: yes

- name: Change deploy directory owner.
  file: >
    path="{{ item.directory }}"
    state=directory
    recurse=yes
    owner={{ item.user }}
    group={{ item.group }}
  with_items: "{{ deploy_sources }}"
  when: deploy_sources|length > 0
  become: yes