---
- name: Install yum-utils.
  yum: >
    name=yum-utils
    state=present
  become: yes

- name: Install EPEL repository.
  yum: >
    name=epel-release
    state=present
  when: yum_repos_repositories.count('epel')
  become: yes

- name: repo list.
  shell: >
    ls /etc/yum.repos.d
  register: repo_list
  changed_when: false
  check_mode: no
- name: Install Remi repository.
  yum: >
    name="{{ yum_repos_remi_rpm_url }}"
    state=present
  when: yum_repos_repositories.count('remi') and repo_list.stdout_lines.count('remi.repo') < 1
  become: yes

- name: Install CentOS6-Base repository(Amazonlinux).
  copy: >
    src=centos6-base.repo
    dest=/etc/yum.repos.d/centos6-base.repo
    mode=0644
  when: ansible_distribution == 'Amazon' and yum_repos_repositories.count('base')
  become: yes

- name: To enable repositories.
  shell: >
    yum-config-manager --enable {{ item }}
  with_items: "{{ yum_repos_repositories }}"
  become: yes