---
- name: Install invoke.
  pip: >
    name=invoke
    state=latest
  environment:
    PATH: "{{ invoke_python_bin_directory }}:{{ ansible_env.PATH }}"

- name: Copy tasks.py.
  copy: >
    src=tasks.py
    dest={{ invoke_tasks_file_directory }}/tasks.py
    mode=0644
    force=yes