---
- name: custom bin directory.
  stat: >
    path={{ invoke_python_bin_directory }}
  register: custom_bin_dir
  changed_when: no
  always_run: yes
  when: invoke_python_bin_directory != ''

- name: Install invoke(default).
  pip: >
    name=invoke
    state=latest
  become: yes
  when: invoke_python_bin_directory == '' or not custom_bin_dir.stat.exists

- name: Install ansible(default).
  command: >
    pip install -U ansible
  become: yes
  when: invoke_python_bin_directory == '' or not custom_bin_dir.stat.exists

- name: Install invoke(custom directory).
  pip: >
    name=invoke
    state=latest
  environment:
    PATH: "{{ invoke_python_bin_directory }}:$PATH"
  when: invoke_python_bin_directory != '' and custom_bin_dir.stat.exists

- name: Install ansible(custom directory).
  command: >
    {{ invoke_python_bin_directory }}/pip install -U ansible
  when: invoke_python_bin_directory != '' and custom_bin_dir.stat.exists

- name: Copy tasks.py.
  copy: >
    src=tasks.py
    dest={{ invoke_tasks_file_directory }}/tasks.py
    mode=0644
    force=yes