---
- name: Install invoke.
  pip: >
    name=invoke
    version=0.12.0
    state=present
  environment:
    PATH: "{{ invoke_python_bin_directory }}:{{ ansible_env.PATH }}"

- name: Copy tasks.py.
  copy: >
    src=tasks.py
    dest={{ invoke_tasks_file_directory }}/tasks.py
    mode=0644
    force=yes
  become: yes

- name: Change tasks.py owner.
  file: >
    path="{{ invoke_tasks_file_directory }}/tasks.py"
    state=file
    owner={{ invoke_user }}
    group={{ invoke_group }}
  become: yes