---
- name: user list.
  shell: >
    cut -d: -f1 /etc/passwd
  register: user_list
  changed_when: false
  check_mode: no
  when: ansible_os_family != 'Darwin'
- name: Create opencv user.
  user: >
    name="{{ opencv_user }}"
    shell=/bin/false
    system=yes
    home="{{ opencv_prefix }}"
    createhome=no
  when: ansible_os_family != 'Darwin' and user_list.stdout_lines.count(opencv_user) < 1
  become: yes

- name: Install/Upgrade dependent packages(RedHat).
  yum: >
    name={{ item.name | default(item) }}
    state={{ item.state | default('latest') }}
  with_items: "{{ opencv_dependent_packages }}"
  when: ansible_os_family == 'RedHat' and opencv_dependent_packages|length > 0
  become: yes
- name: Install dependent packages(Darwin).
  homebrew: >
    name={{ item.name | default(item) }}
    state={{ item.state | default('latest') }}
    install_options={{ item.install_option | default('') }}
  with_items: "{{ opencv_dependent_packages }}"
  when: ansible_os_family == 'Darwin' and opencv_dependent_packages|length > 0

- name: Create work directory.
  file: >
    path="{{ opencv_work_directory }}"
    state=directory
    owner="{{ opencv_user }}"
    group="{{ opencv_group }}"
    mode=0755
  become: yes

- name: Extract Source code.
  unarchive: >
    src={{ opencv_source_url }}
    dest={{ opencv_work_directory }}
    copy=no
    mode=0755
  become: yes

- name: Extract Contrib Source code.
  unarchive: >
    src={{ opencv_contrib_source_url }}
    dest={{ opencv_work_directory }}
    copy=no
    mode=0755
  become: yes

- name: Cmake, Make and Install.
  shell: "{{ item }}"
  args:
    chdir: "{{ opencv_work_directory }}/opencv-{{ opencv_version }}"
  with_items:
    - >-
      LD_LIBRARY_PATH={{ opencv_ffmpeg_prefix }}/lib/
      PKG_CONFIG_PATH=$PKG_CONFIG_PATH:{{ opencv_ffmpeg_prefix }}/lib/pkgconfig
      PKG_CONFIG_LIBDIR=$PKG_CONFIG_LIBDIR:{{ opencv_ffmpeg_prefix }}/lib
      cmake
      -DCMAKE_INSTALL_PREFIX={{ opencv_prefix }}
      -DCMAKE_BUILD_TYPE=RELEASE
      -DOPENCV_EXTRA_EXE_LINKER_FLAGS="-Wl,-rpath,{{ opencv_ffmpeg_prefix }}/lib"
      -DBUILD_TESTS=OFF
      -DBUILD_EXAMPLES=ON
      -DPYTHON_DEFAULT_EXECUTABLE={{ opencv_python_bin_directory }}/python
      -DOPENCV_EXTRA_MODULES_PATH={{ opencv_work_directory }}/opencv_contrib-{{ opencv_version }}/modules
      -DBUILD_opencv_legacy=OFF
      {{ opencv_work_directory }}/opencv-{{ opencv_version }}
    - make
    - make install
  become: yes

- name: Remove work directory.
  file: >
    path="{{ opencv_work_directory }}"
    state=absent
  become: yes

- name: Change opencv directory owner.
  file: >
    path="{{ opencv_prefix }}"
    state=directory
    recurse=yes
    owner="{{ opencv_user }}"
    group="{{ opencv_group }}"
  become: yes

- name: Install python packages.
  pip: >
    name={{ item }}
    state=latest
    executable={{ opencv_python_bin_directory }}/pip
  with_items: "{{ opencv_python_install_packages }}"
  when: opencv_python_install_packages|length > 0

- name: Insert env in .envrc.
  lineinfile: >
    dest={{ opencv_envrc_directory }}/.envrc
    line="{{ item.value }}"
    insertafter=EOF
    state=present
    regexp={{ item.regexp }}
  with_items: "{{ opencv_environment_variables }}"
  when: opencv_envrc_directory != '' and opencv_environment_variables|length > 0
