---
- name: Create terraform aws directory.
  file: >
    path="{{ terraform_aws_directory }}"
    state=directory
    owner={{ terraform_aws_user }}
    group={{ terraform_aws_group }}
    mode=0755
  become: yes

- name: Clone skel.
  git: >
    repo="{{ terraform_aws_skel_repository }}"
    dest="{{ terraform_aws_directory }}/{{ item }}"
    update=no
    track_submodules=yes
    accept_hostkey=yes
  with_items: terraform_aws_environments
  when: terraform_aws_environments|length > 0

- name: Replace environment in config.tf.
  lineinfile: >
    dest={{ terraform_aws_directory }}/{{ item }}/config.tf
    line="  default = \"{{ item }}\""
    insertafter=EOF
    state=present
    regexp="^\s+default\s=\s\".+\"$"
  with_items: terraform_aws_environments
  when: terraform_aws_environments|length > 0

- name: Remove README.md.
  file: >
    path="{{ terraform_aws_directory }}/{{ item }}/README.md"
    state=absent
  with_items: terraform_aws_environments
  when: terraform_aws_environments|length > 0

- name: Insert env in .envrc.
  lineinfile: >
    dest={{ terraform_aws_envrc_directory }}/.envrc
    line="{{ item.value }}"
    insertafter=EOF
    state=present
    regexp={{ item.regexp }}
  with_items: terraform_aws_environment_variables
  when: terraform_aws_envrc_directory != '' and terraform_aws_environment_variables|length > 0
