---
- name: Clone skel.
  git: >
    repo="{{ terraform_skel_repository }}"
    dest="{{ terraform_directory }}/{{ item }}"
    update=no
    track_submodules=yes
    accept_hostkey=yes
  with_items: terraform_environments
  when: terraform_environments|length > 0

- name: Insert env in .envrc.
  lineinfile: >
    dest={{ terraform_envrc_directory }}/.envrc
    line="{{ item.value }}"
    insertafter=EOF
    state=present
    regexp={{ item.regexp }}
  with_items: terraform_environment_variables
  when: terraform_envrc_directory != '' and terraform_environment_variables|length > 0
