---
- name: Install celery packages.
  pip: >
    name={{ item }}
    state=latest
  with_items: "{{ celery_install_packages }}"
  environment:
    PATH: "{{ celery_python_bin_directory }}:{{ ansible_env.PATH }}"
  when: celery_install_packages|length > 0

- name: Create celery conf directory.
  file: >
    path="{{ celery_conf_directory }}"
    state=directory
    owner="{{ celery_user }}"
    group="{{ celery_group }}"
    mode=0755
  become: yes
- name: Create celery config file.
  template: >
    src=celery.conf.tpl
    dest="{{ celery_conf_directory }}/{{ celery_conf_file_name }}"
    owner="{{ celery_user }}"
    group="{{ celery_group }}"
    mode=0644
- name: Create celery log directory.
  file: >
    path="{{ celery_log_directory }}"
    state=directory
    owner="{{ celery_user }}"
    group="{{ celery_group }}"
    mode=0755
  become: yes
- name: Create celery pid directory.
  file: >
    path="{{ celery_pid_directory }}"
    state=directory
    owner="{{ celery_user }}"
    group="{{ celery_group }}"
    mode=0755
  become: yes

- name: Reload supervisord service.
  service: >
    name=supervisord
    state=reloaded
  when: ansible_system == 'Linux'
