---
- name: Install django packages.
  pip: >
    name={{ item }}
    state=latest
  with_items: django_install_packages
  environment:
    PATH: "{{ xbuild_python_bin_directory }}:{{ ansible_env.PATH }}"
  when: django_install_packages|length > 0

- name: Clone project directory.
  git: >
    repo="{{ django_repository }}"
    dest="{{ django_directory }}/{{ django_project }}"
    update=yes
  when: django_repository

- name: Create project directory.
  command: >
    django-admin startproject {{ django_project }}
  args:
    chdir: "{{ django_directory }}"
    creates: "{{ django_directory }}/{{ django_project }}"
  environment:
    PATH: "{{ xbuild_python_bin_directory }}:{{ ansible_env.PATH }}"
  when: not django_repository

- name: Create project directory.
  command: >
    django-admin startapp {{ item }}
  args:
    chdir: "{{ django_directory }}/{{ django_project }}"
    creates: "{{ django_directory }}/{{ django_project }}/{{ item }}"
  with_items: django_apps
  environment:
    PATH: "{{ xbuild_python_bin_directory }}:{{ ansible_env.PATH }}"
  when: django_apps|length > 0

- name: Change django project directory owner.
  file: >
    path="{{ django_directory }}/{{ django_project }}"
    state=directory
    recurse=yes
    owner={{ django_user }}
    group={{ django_group }}
  become: yes
