---
- name: custom bin directory.
  stat: >
    path={{ django_python_bin_directory }}
  register: custom_bin_dir
  changed_when: no
  always_run: yes
  when: django_python_bin_directory != ''

- name: Install django packages(default).
  pip: >
    name={{ item }}
    state=latest
  with_items: django_install_packages
  become: yes
  when: django_install_packages|length > 0 and (invoke_python_bin_directory == '' or not custom_bin_dir.stat.exists)

- name: Install django packages(custom python).
  pip: >
    name={{ item }}
    state=latest
  with_items: django_install_packages
  environment:
    PATH: "{{ django_python_bin_directory }}:$PATH"
  when: django_install_packages|length > 0 and invoke_python_bin_directory != '' and custom_bin_dir.stat.exists

- name: Clone project directory.
  git: >
    repo="{{ django_repository }}"
    dest="{{ django_directory }}/{{ django_project }}"
    update=yes
  when: django_repository


- name: Create project directory(default).
  command: >
    django-admin startproject {{ django_project }}
  args:
    chdir: "{{ django_directory }}"
    creates: "{{ django_directory }}/{{ django_project }}"
  when: 
  when: not django_repository and (invoke_python_bin_directory == '' or not custom_bin_dir.stat.exists)

- name: Create project directory(custom python).
  command: >
    django-admin startproject {{ django_project }}
  args:
    chdir: "{{ django_directory }}"
    creates: "{{ django_directory }}/{{ django_project }}"
  environment:
    PATH: "{{ django_python_bin_directory }}:$PATH"
  when: not django_repository and invoke_python_bin_directory != '' and custom_bin_dir.stat.exists

- name: Create app directory(default).
  command: >
    django-admin startapp {{ item }}
  args:
    chdir: "{{ django_directory }}/{{ django_project }}"
    creates: "{{ django_directory }}/{{ django_project }}/{{ item }}"
  with_items: django_apps
  when: django_apps|length > 0 and (invoke_python_bin_directory == '' or not custom_bin_dir.stat.exists)

- name: Create project directory(custom python).
  command: >
    django-admin startapp {{ item }}
  args:
    chdir: "{{ django_directory }}/{{ django_project }}"
    creates: "{{ django_directory }}/{{ django_project }}/{{ item }}"
  with_items: django_apps
  environment:
    PATH: "{{ django_python_bin_directory }}:$PATH"
  when: not django_apps|length > 0 and invoke_python_bin_directory != '' and custom_bin_dir.stat.exists

- name: Change django project directory owner.
  file: >
    path="{{ django_directory }}/{{ django_project }}"
    state=directory
    recurse=yes
    owner={{ django_user }}
    group={{ django_group }}
  become: yes
