---
- name: Clone prezto repository.
  git: >
    repo={{ prezto_repository }}
    dest={{ ansible_user_dir }}/.zprezto
    update=yes
    recursive=yes
    track_submodules=yes
    accept_hostkey=yes

- name: .zshrc.
  stat: >
    path={{ ansible_user_dir }}/.zshrc
  register: zshrc
  changed_when: no
  check_mode: no

- name: Copy bootstrap.
  template: >
    src=bootstrap.tpl
    dest={{ ansible_user_dir }}/bootstrap
    mode=0755
  when: not zshrc.stat.exists
- name: Excute bootstrap.sh.
  shell: >
    ./bootstrap
  args:
    chdir: {{ ansible_user_dir }}
  when: not zshrc.stat.exists
- name: Remove bootstrap.
  file: >
    path={{ ansible_user_dir }}/bootstrap
    state=absent
  when: not zshrc.stat.exists