---
- name: Prezto directory.
  stat: >
    path={{ ansible_user_dir }}/.zprezto
  register: res
  changed_when: False
  always_run: yes
- name: Clone prezto repository.
  git: >
    repo={{ prezto_repository }}
    dest={{ ansible_user_dir }}/.zprezto
    force=yes
    recursive=yes
    track_submodules=yes
    accept_hostkey=yes
  when: not res.stat.exists

- name: Copy bootstrap.
  template: >
    src=bootstrap.tpl
    dest={{ ansible_user_dir }}/bootstrap
    mode=0755
  when: not res.stat.exists
- name: Excute bootstrap.sh.
  shell: >
    ./bootstrap
  args:
    chdir: {{ ansible_user_dir }}
  when: not res.stat.exists
- name: Remove bootstrap.
  file: >
    path={{ ansible_user_dir }}/bootstrap
    state=absent
  when: not res.stat.exists