---
- name: Set localtime.
  copy: >
    src="/usr/share/zoneinfo/{{ timezone }}"
    dest="/etc/localtime"
    owner=root
    group=root
    mode=0644
  become: yes

- name: Change clock file.
  template: >
    src="clock.tpl"
    dest="/etc/sysconfig/clock"
    owner=root
    group=root
    mode=0644
  become: yes

- name: Reflect clock file.
  shell: source /etc/sysconfig/clock
  become: yes
