---
- name: Install td-agent(RedHat).
  shell: >
    curl -L https://toolbelt.treasuredata.com/sh/install-redhat-td-agent2.sh | sh
  become: yes
  when: ansible_os_family == 'RedHat'

- name: Install td-agent plugins.
  command: >
    {{ td_agent_gem_bin_file }} install {{ item }}
  with_items: "{{ td_agent_plugins }}"
  become: yes
  when: ansible_os_family == 'RedHat' and td_agent_plugins|length > 0

- name: Register td-agent service.
  service: >
    name=td-agent
    enabled="{{ td_agent_service_enabled }}"
  become: yes

- name: Insert settings in awslogs.conf.
  lineinfile: >
    dest=/etc/awslogs/awslogs.conf
    line="{{ td_agent_awslogs_settings }}"
    insertafter=EOF
    state=present
    regexp="^\[/var/log/td-agent/td-agent.log\]"
  become: yes
