---
- name: Install dependent packages(RedHat).
  yum: >
    name={{ item.name | default(item) }}
    state={{ item.state | default('latest') }}
  become: yes
  with_items: "{{ chrome_driver_dependent_packages }}"
  when: ansible_os_family == 'RedHat' and chrome_driver_dependent_packages|length > 0

- name: Install google-chrome repository(RedHat).
  copy: >
    src=google-chrome.repo
    dest=/etc/yum.repos.d/google-chrome.repo
    mode=0644
  when: ansible_os_family == 'RedHat'
  become: yes

- name: Install google-chrome-stable(RedHat).
  yum: >
    name=google-chrome-stable
    state=present
  when: ansible_os_family == 'RedHat'
  become: yes

- name: Install chrome-driver.
  unarchive: >
    src={{ chrome_driver_url }}
    dest={{ chrome_driver_bin_directory }}
    copy=no
  become: yes

