---
- name: Insert of limits.conf.
  lineinfile: >
    dest="{{ os_conf_limits_conf_file }}"
    line="{{ item.value }}"
    insertafter=EOF
    state=present
    regexp={{ item.regexp }}
  with_items: "{{ os_conf_limits_conf_variables }}"
  become: yes

- name: sysconf init file(CentOS 6.x).
  stat: >
    path="{{ os_conf_sysconfig_init_file }}"
  register: sysconf_init
  changed_when: no
  check_mode: no
- name: Insert of initscript.
  lineinfile: >
    dest="{{ os_conf_sysconfig_init_file }}"
    line="{{ item.value }}"
    insertafter=EOF
    state=present
    regexp={{ item.regexp }}
  with_items: "{{ os_conf_sysconfig_init_variables }}"
  when: sysconf_init.stat.exists
  become: yes

- name: Insert of sysctl.conf.
  lineinfile: >
    dest="{{ os_conf_sysctl_conf_file }}"
    line="{{ item.value }}"
    insertafter=EOF
    state=present
    regexp={{ item.regexp }}
  with_items: "{{ os_conf_sysctl_conf_variables }}"
  become: yes