---
- name: Insert of limits.conf.
  lineinfile: >
    dest="{{ os_limits_conf_file }}"
    line="{{ item.value }}"
    insertafter=EOF
    state=present
    regexp={{ item.regexp }}
  with_items:
    - regexp: '^root soft nofile.+'
      value: 'root soft nofile {{ os_conf_ulimit }}'
    - regexp: '^root hard nofile.+'
      value: 'root hard nofile {{ os_conf_ulimit }}'
    - regexp: '^\* soft nofile.+'
      value: '* soft nofile {{ os_conf_ulimit }}'
    - regexp: '^\* hard nofile.+'
      value: '* hard nofile {{ os_conf_ulimit }}'
  become: yes

- name: sysconf init file(CentOS 6.x).
  stat: >
    path="{{ os_sysconf_init_file }}"
  register: sysconf_init
  changed_when: no
  check_mode: no
- name: Insert of initscript.
  lineinfile: >
    dest="{{ os_sysconf_init_file }}"
    line="{{ item.value }}"
    insertafter=EOF
    state=present
    regexp={{ item.regexp }}
  with_items:
    - regexp: '^ulimit -n .+'
      value: 'ulimit -n {{ os_conf_ulimit }}'
  when: sysconf_init.stat.exists
  become: yes

- name: Insert of sysctl.conf.
  lineinfile: >
    dest="{{ os_sysctl_file }}"
    line="{{ item.value }}"
    insertafter=EOF
    state=present
    regexp={{ item.regexp }}
  with_items:
    - regexp: '^net\.ipv4\.tcp_tw_recycle\s=.+'
      value: 'net.ipv4.tcp_tw_recycle = {{ os_conf_net_ipv4_tcp_tw_recycle }}'
    - regexp: '^net.ipv4.tcp_tw_reuse =.+'
      value: 'net.ipv4.tcp_tw_reuse = {{ os_conf_net_ipv4_tcp_tw_reuse }}'
    - regexp: '^net.ipv4.ip_local_port_range =.+'
      value: 'net.ipv4.ip_local_port_range = {{ os_conf_net_ipv4_ip_local_port_range }}'
    - regexp: '^net.ipv4.tcp_keepalive_time =.+'
      value: 'net.ipv4.tcp_keepalive_time = {{ os_conf_net_ipv4_tcp_keepalive_time }}'
    - regexp: '^net.ipv4.tcp_keepalive_probes =.+'
      value: 'net.ipv4.tcp_keepalive_probes = {{ os_conf_net_ipv4_tcp_keepalive_probes }}'
    - regexp: '^net.ipv4.tcp_keepalive_intvl =.+'
      value: 'net.ipv4.tcp_keepalive_intvl = {{ os_conf_net_ipv4_tcp_keepalive_intvl }}'
  become: yes