---
- name: user list.
  shell: >
    cut -d: -f1 /etc/passwd  
  register: user_list  
  changed_when: false  
  always_run: yes 
- name: Create openresty user.
  user: >
    name="{{ openresty_user }}"
    shell=/bin/false
    system=yes
    home="{{ openresty_nginx_prefix }}/nginx"
    createhome=no
  when: user_list.stdout_lines.count(openresty_user) < 1 
  become: yes

- name: Install dependent packages.
  yum: >
    name="{{ item }}"
    state="present"
  with_items: "{{ openresty_dependent_packages }}"
  become: yes
  when: openresty_dependent_packages|length > 0

- name: Create source directory.
  file: >
    path="{{ openresty_src_directory }}/openresty-{{ openresty_version }}"
    state=directory
    owner="{{ openresty_user }}"
    group="{{ openresty_user }}"
    mode=0755
  become: yes
- name: Extract openresty source.
  unarchive: >
    src="http://openresty.org/download/openresty-{{ openresty_version }}.tar.gz"
    dest="{{ openresty_src_directory }}/openresty-{{ openresty_version }}"
    copy=no
  become: yes

archive_file