---
- name: Node directory.
  stat: >
    path={{ xbuild_node_install_directory }}
  register: node_directory
  changed_when: no
  always_run: yes
- name: Install node in xbuild.
  command: >
    {{ xbuild_install_directory }}/node-install {{ xbuild_node_version }}
    {{ xbuild_node_install_directory }} {{ xbuild_node_arch }}
  when: not node_directory.stat.exists
  become: yes

- name: Change node directory owner.
  file: >
    path={{ xbuild_node_install_directory }}
    state=directory
    recurse=yes
    owner={{ xbuild_node_user }}
    group={{ xbuild_node_group }}
  become: yes

- name: Install node packages.
  npm: >
    name={{ item }}
    executable={ xbuild_node_install_directory }}/bin/npm
    global=yes
  with_items: "{{ xbuild_node_packages }}"
  when: xbuild_node_packages|length > 0

- name: Insert env in .envrc.
  lineinfile: >
    dest={{ xbuild_node_envrc_directory }}/.envrc
    line="{{ item.value }}"
    insertafter=EOF
    state=present
    regexp={{ item.regexp }}
  with_items: "{{ xbuild_node_environment_variables }}"
  when: xbuild_node_envrc_directory != '' and xbuild_node_environment_variables|length > 0

- name: Remove xbuild directory.
  file: >
    path={{ xbuild_install_directory }}
    state=absent
  when: xbuild_node_remove_xbuild
  become: yes
