---
- name: Install/Update packer.
  homebrew_cask: >
    name=packer
    state=present
  environment: 
    HOMEBREW_CASK_OPTS: "{{ homebrew_cask_options }}"

- name: Packer directory.
  stat: >
    path={{ packer_directory }}
  register: pckr_directory 
  changed_when: no
  always_run: yes
- name: Create packer directory.
  file: >
    path="{{ packer_directory }}"
    state=directory
    owner={{ packer_user }}
    group={{ packer_group }}
    mode=0755
  when: not pckr_directory.stat.exists
  become: yes

- name: amazon-ebs json.
  stat: >
    path="{{ packer_amazon_ebs_file }}"
  register: amazon_ebs_file
  changed_when: no
  always_run: yes
- name: Create template json.
  copy: >
    src=amazon_ebs.json
    dest={{ packer_amazon_ebs_file }}
    owner={{ packer_user }}
    group={{ packer_group }}
    mode=0644
  when: not amazon_ebs_file.stat.exists
  become: yes

- name: Insert env in .envrc.
  lineinfile: >
    dest={{ packer_envrc_directory }}/.envrc
    line="{{ item.value }}"
    insertafter=EOF
    state=present
    regexp={{ item.regexp }}
  with_items: packer_environment_variables
  when: packer_envrc_directory != '' and packer_environment_variables|length > 0
