- name: Install dependent packages(Amazon Linux).
  yum: >
    name={{ item.name | default(item) }}
    state={{ item.state | default('latest') }}
  with_items: "{{ gtk_firefox_dependent_packages }}"
  when: ansible_distribution == 'Amazon' and gtk_firefox_dependent_packages|length > 0
  become: yes

- name: Download install shell.
  get_url: >
    url={{ gtk_firefox_install_shell_url}}
    dest={{ gtk_firefox_install_shell_file }}
    mode=0755
  when: ansible_distribution == 'Amazon'
  become: yes

- name: Replace archive url.
  lineinfile: >
    dest={{ gtk_firefox_install_shell_file }}
    regexp='^(.+)http://download.cdn.mozilla.net.+$'
    line="\1{{ gtk_firefox_install_archive_url }}"
    state=present
    insertafter=EOF
    backrefs=yes
  when: ansible_distribution == 'Amazon'
  become: yes

- name: Install gtk-firefox.
  shell: >
    {{ gtk_firefox_install_shell_file }}
  when: ansible_distribution == 'Amazon'
  become: yes

- name: Remove libpixman-1.so.0.
  file: >
    path=/usr/local/lib/libpixman-1.so.0
    state=absent
  when: ansible_distribution == 'Amazon'
  become: yes